apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: odf-node-label-job
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: ocp-default
      requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: odf-node-label-job-{{name}}
    spec:
      destination:
        namespace: openshift-storage
        server: '{{server}}'
      project: default
      source:
        path: openshift-data-foundation-operator/config-helpers/node-labeler/overlays/default
        repoURL: https://github.com/robertsandoval/scratch.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
