apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: KnativeEventing.v1beta1.operator.knative.dev,KnativeKafka.v1alpha1.operator.serverless.openshift.io,KnativeServing.v1beta1.operator.knative.dev
  generateName: openshift-serverless-
  name: openshift-serverless-dxt8t
  namespace: openshift-serverless
spec:
  upgradeStrategy: Default
